### PR TITLE
Feat/budgets graph

### PR DESCRIPTION
**Pull request by j721**
Description: 
created Budgets graph component using Plotly and exported through index.js in graphs folder. Imported Budgets graph into the renderHomePage component

Type of Change: 
creating a feature

### CODE REVIEW

**Review by kwmorlock — APPROVED** [review]
Looks good!

**Review by HNelson98 — COMMENTED** [review]
Thanks for the detailed commits!

**Review by tonyrkovar — CHANGES_REQUESTED** [review]
Could you add ComparedSavings to the import on line 4 and delete line 5 to save space.

**Review by tonyrkovar — APPROVED** [review]
Thank you for taking care of that!

**Pull request merged**
