### PR TITLE
Fix/budget auth

### PR DESCRIPTION
**Pull request by HNelson98**
Heading/Title

Replaced dummy data code with dynamic code and added container for state

Description

Replaced dummy data code with dynamic code and added container for state and fixed an issue where authentication wasn't happening

Fixes 

 fixed an issue where authentication wasn't happening

Type of Change
fix

### CODE REVIEW

**Review by j721 — APPROVED** [review]
Great fix for getting the authorization for the Budgets component to work

**Review by kwmorlock — APPROVED** [review]
Looks great!

**Review by kwmorlock — APPROVED** [review]
Looks great!

**Review by SSWSpencer — APPROVED** [review]
Looks great!

**Pull request merged**
