### PR TITLE
Deleted unnecessary boilerplate files

### PR DESCRIPTION
**Pull request by SSWSpencer**
### Deleted Unnecessary Boilerplate Files

**Description**
Removed and cleaned up a bit of the file structure for the repo. Deleted unusable files and tests associated with those files.
 

**Fixes** 
- Removed a few of the unnecessary boilerplate files that will not be used again
- Removed lines that reference the deleted files (imports, etc)
- Removed tests that were associated with the deleted files
- Added comments to files that will likely be deleted at a later date, but currently serve as good examples

### CODE REVIEW

**Review by kwmorlock — APPROVED** [review]
Awesome work with the removal of those boilerplate files.

**Review by j721 — APPROVED** [review]
really good description on the changes made to the file structure

**Review by HNelson98 — APPROVED** [review]
Nice commits!

**Review by mbidnyk1 — APPROVED** [review]
Looks clean.

**Pull request merged**
