### PR TITLE
Chore/readmefrontend

### PR DESCRIPTION
**Pull request by kwmorlock**
Heading/Title
Readme update

Description
Updated readme with product overview and feature overview sections

Type of Change
Chore

### CODE REVIEW

**Review by j721 — APPROVED** [review]
readme changes look good!

**Review by SSWSpencer — APPROVED** [review]
Looks good, great work!

**Review by mbidnyk1 — APPROVED** [review]
Good job on the readme

**Review by HNelson98 — APPROVED** [review]
Thanks for your hard work!

**Pull request merged**
