### PR TITLE
Chore/update/styling

### PR DESCRIPTION
**Pull request by j721**
Chore/update/styling

Description
- updated styling for Navbar and Navbuttons for responsivness

Type of Change
chore- styling

### CODE REVIEW

**Review by kwmorlock — APPROVED** [review]
Great, thanks!

**Review by kwmorlock — APPROVED** [review]
Great, thanks!

**Review by mbidnyk1 — APPROVED** [review]
Styling changes look clean

**Review by SSWSpencer — APPROVED** [review]
Looks great!

**Review by HNelson98 — APPROVED** [review]
Thanks for your hard work!

**Pull request merged**
