### PR TITLE
Chore/mobile styling

### PR DESCRIPTION
**Pull request by SSWSpencer**
### Heading/Title
Added Styling for Mobile Application

**should be descriptive and concise related to the main purpose of the pull request 

**Description**
Did a bunch of styling/reworking of components to make it look better and be more user-friendly on the mobile application

**Fixes** 
- Rewrote the graph carousel component to allow easier addition of new graphs (just add a new component as inside of <GraphCarousel> </GraphCarousel> inside of RenderHomePage.js)
- Rewrote the graph carousel component to have a sliding animation between graphs
- Rewrote the graph carousel component to support mobile swipe gestures
- Added description text under three of the graphs to be more similar and take up a comparable amount of page space as the Budgets graph
- Changed the layout properties of all of the graphs to be responsive to the size of their div (opposed to the hard-coded length/width attributes)

**Type of Change**
If this wasn't a chore I don't know what is

### CODE REVIEW

**Review by kwmorlock — APPROVED** [review]
Amazing job with the mobile styling

**Review by HNelson98 — APPROVED** [review]
Looks great! good work on the carousel

**Review by j721 — APPROVED** [review]
Styling looks really great, including a carousel and swipe feature for mobile is great an idea.

**Review by tonyrkovar — APPROVED** [review]
Good work on this, be careful for conflicts moving forward.

**Pull request merged**
