### PR TITLE
Chore: added an image folder in public with logo

### PR DESCRIPTION
**Pull request by JesusCGuerrero**
Pull Request Guidelines

Heading/Title

**should be descriptive and concise related to the main purpose of the pull request 

Description

**accurately describes the main purpose of what the changes are doing
**provide links when necessary for the code that's being changed

Fixes 

**describe what type of fix is being made (syntax, spelling error, etc.) 
    **specific bug fix provide a link in the description 
**and what problem it is fixing

Type of Change

**describe type of change is being made (bug fix, creating new feature, downloading dependencies)

Commits

should be descriptive, concise, accurate, and frequent

Size

number of files changed should be limited to 5 at most

Reviewers

pull request should have at least two team members reviewing 
and providing appropriate comments 

Code
should be clear and readable
comments are made when necessary 
should have few instances of duplicate and dead code
should follow industry standards

### CODE REVIEW

**Review by kwmorlock — APPROVED** [review]
Great getting image ready to display.

**Review by j721 — APPROVED** [review]
looks good

**Review by SSWSpencer — APPROVED** [review]
Good description. Beautiful picture.

**Review by mbidnyk1 — APPROVED** [review]
Looking good!

**Review by kwmorlock — APPROVED** [review]
Great work!

**Pull request merged**
