### PR TITLE
feat/nav/nav.js

### PR DESCRIPTION
**Pull request by JesusCGuerrero**
Pull Request Guidelines

Heading/Title

**should be descriptive and concise related to the main purpose of the pull request 

Description

**accurately describes the main purpose of what the changes are doing
**provide links when necessary for the code that's being changed

Fixes 

**describe what type of fix is being made (syntax, spelling error, etc.) 
    **specific bug fix provide a link in the description 
**and what problem it is fixing

Type of Change

**describe type of change is being made (bug fix, creating new feature, downloading dependencies)

Commits

should be descriptive, concise, accurate, and frequent

Size

number of files changed should be limited to 5 at most

Reviewers

pull request should have at least two team members reviewing 
and providing appropriate comments 

Code
should be clear and readable
comments are made when necessary 
should have few instances of duplicate and dead code
should follow industry standards

### CODE REVIEW

**Review by HNelson98 — APPROVED** [review]
Looks Good! thanks for making this, We might want to change the name of the PR to a Feature, and the commit of creating the nav component to a feature as well.

**Review by mbidnyk1 — APPROVED** [review]
Navbar looks clean, good job!

**Comment by Vyraal1** [comment]
Per conversation with Tony
* should have those notes at the bottom at commits and below dropped in the slack and discord so it's easy to find

Overall solid pull requests, there are a couple of nitpicks as we discussed in the Zoom call regarding it being labeled as a feature as well as some improved description in the content.

8/10, I would recommend this PR to future employers, but I would not frame it and tell it to my grandchildren for generations later to come.

**Review by j721 — APPROVED** [review]
Commits are descriptive. Navbar looks nice on the home page!  One fix for one the commits is creating the NavBar component should be labeled as a Feat. Also, adding a message in the pull request description would be good as well. But, overall looks really good!

**Review by tonyrkovar — CHANGES_REQUESTED** [review]
Hey Jesus, 

Like we talked about in the zoom meeting would you be able to go into your FE repo and edit the pull_request_template.md with the changes we said verbally? 

Once you do that I'll look it over again!

**Review by tonyrkovar — APPROVED** [review]
Thank you for fixing this!

**Pull request merged**
